version: '3'
services:
  app:
    image: 'node:10-alpine'
    working_dir: /app
    ports:
      - 80:80
      - 443:443
    command: npm run build_n_run
    # networks:
    #   - proxy
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      # - sslcerts:/acme

# volumes:
#   sslcerts:
#     external: true

# networks:
#   proxy:
#     external: true